In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4])
print(vector)

[1 2 3 4]


In [3]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
matriz.shape

(3, 3)

In [6]:
matriz_t = matriz.T #Transponer matrices
print(matriz_t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## PRODUCTO INTERNO DE MATRICES 

In [10]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
B = np.array([[2,3], [5,7], [11,13]])
C = A.dot(B)
print(C)

[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]
